name: Setup

on:
  workflow_call:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - name: Cache Dependencies
      id: node-modules-cache
      uses: actions/cache@v4
      with:
        path: |
          node_modules
        key: modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      run: npm ci
